[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=blcncmsvmcqlqgnfptcy&read_only=true&features=docs%2Caccount%2Cdatabase%2Cdebugging%2Cdevelopment%2Cfunctions%2Cbranching"

[mcp_servers.mobbin]
url = "https://api.mobbin.com/mcp"

[mcp_servers.dataforseo]
command = "npx"
args = ["-y", "dataforseo-mcp-server"]

[mcp_servers.dataforseo.env]
DATAFORSEO_USERNAME = "devanshughosh98@gmail.com"
DATAFORSEO_PASSWORD = "35f3d544dde2f046"
